USE DEMO;
SELECT * FROM DEPOSIT;
CREATE VIEW EMPLOYEEDATA AS
    SELECT 
        DEPOSIT.ACTNO, DEPOSIT.CNAME, BRANCH.CITY
    FROM
        DEPOSIT
            INNER JOIN
        BRANCH ON DEPOSIT.BNAME = BRANCH.BNAME;
SELECT * FROM employeedata;

SHOW DATABASES;
USE DEMO ;
SELECT * FROM PRODUCTS;
CREATE VIEW  PRODUCTO  AS
SELECT 
    PRODUCTID, PRODUCTNAME
FROM
    PRODUCTS
WHERE
    PRICE > (SELECT 
            AVG(SUPPLIERID)
        FROM
            PRODUCTS);
SELECT * FROM PRODUCTO;